#!/bin/bash

# no-wing Deno Final Installer
# Creates a global no-wing command using Deno

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

print_color() {
    local color=$1
    shift
    echo -e "${color}$*${NC}"
}

main() {
    print_color "$CYAN" "🛫 no-wing Deno Final Installer"
    echo
    
    # Check if we're in the right directory
    if [[ ! -f "deno/no-wing.ts" ]]; then
        print_color "$RED" "❌ Please run this from the no-wing project directory"
        print_color "$YELLOW" "Expected to find: deno/no-wing.ts"
        exit 1
    fi
    
    # Find Deno
    local deno_path
    if deno_path=$(which deno 2>/dev/null); then
        print_color "$GREEN" "✅ Found Deno: $deno_path"
    else
        print_color "$RED" "❌ Deno not found"
        print_color "$YELLOW" "Install Deno first:"
        print_color "$YELLOW" "  curl -fsSL https://deno.land/x/install/install.sh | sh"
        print_color "$YELLOW" "  # Then add to PATH: export PATH=\"\$HOME/.deno/bin:\$PATH\""
        exit 1
    fi
    
    # Get absolute paths
    local project_dir
    project_dir=$(pwd)
    local deno_script="$project_dir/deno/no-wing.ts"
    
    # Create system wrapper
    local wrapper_path="/usr/local/bin/no-wing"
    
    print_color "$CYAN" "🔧 Creating global no-wing command..."
    
    sudo tee "$wrapper_path" > /dev/null << EOF
#!/bin/bash
# no-wing global wrapper (Deno) - generated by install-deno-final.sh
# Deno: $deno_path
# Script: $deno_script

exec "$deno_path" run --allow-all "$deno_script" "\$@"
EOF
    
    sudo chmod +x "$wrapper_path"
    
    print_color "$GREEN" "✅ Global command created: $wrapper_path"
    
    # Test the wrapper
    print_color "$CYAN" "🧪 Testing installation..."
    
    if no-wing --version >/dev/null 2>&1; then
        print_color "$GREEN" "✅ Installation successful!"
        echo
        print_color "$YELLOW" "🚀 Usage:"
        echo "  no-wing setup        # Create Q service account"
        echo "  no-wing status       # Check service account"
        echo "  no-wing launch       # Launch Q with service account"
        echo "  no-wing aws-setup    # Configure AWS credentials"
        echo "  no-wing cleanup      # Remove service account"
        echo
        print_color "$GREEN" "✨ Key Benefits:"
        echo "  ✅ No sudo required for daily use"
        echo "  ✅ No Node.js dependencies"
        echo "  ✅ No build step required"
        echo "  ✅ Single binary execution"
        echo "  ✅ Cross-platform compatibility"
        echo "  ✅ Built-in TypeScript support"
        echo
        print_color "$CYAN" "💡 Try it now:"
        echo "  cd your-project && no-wing setup"
        echo
        print_color "$YELLOW" "📚 Documentation:"
        echo "  https://github.com/pchinjr/no-wing"
    else
        print_color "$RED" "❌ Installation test failed"
        exit 1
    fi
}

main "$@"
